# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9909441f5e1b51e8c803d2894c5bafea3ae4e663878ea6c5b36508d82de70092080ca799b4d3ad574e5c1e8de3659620e5c032e34c52e6bdaee2204b5e3bcaf

test:
  secret_key_base: 3d4f711cddf674dd92222b8e3baa3b38738b8346281c3a3db2a429a666807a832d4e8daf1a839f6a6c65740665234fab6404065139263065d5052257b3dad806

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
